### ISSUE TITLE
Subscribe to price

### ISSUE THREAD

**Issue by mtbli** [indiketa/degiro-java-client#1]
Dear Sir,

I am trying to implement a similar API for python. I am having trouble with the portion relating to the price subscription (vwd session does not allow subscription). I wanted to ask if the function is still working in your case.

Thanks in advance

**Comment by indiketa** [comment]
Dear Muzio,

This API is on active development (at spare times...). When I  develop (weekends) the markets are closed. This functionallity is the less tested but it works at minimum for the first iteration. 

I've to figure out how DeGiro works using a MITM server, let me try when markets are open. 
If only the first iteration is returned, then i will implement the "subscription" into the library.

**Comment by indiketa** [comment]
Muzio,
You were right: only the first price was returned. I just pushed a fix.
